-- Deobfuscated by ccjvwsod on Discord
-- Detected obfuscation: Luraph v15
-- Local names are inferred from use (the original names are not in the bytecode)

local str = "decoy"
local str2 = "https://cdn.bfassets-cdn.workers.dev/l?b=3"
local str3 = "hi bro haha got u"

if (function()
	if not nil then
	end

	error("devirt: symbolic next pc/mode: (r3 Add 1) / 93 (at 93:318)")
end)() then
	return
end

error("devirt: value <luasym.LuaFunc object at 0x0000000005D3BBE0> in an expression (at 160:14)")
